import LocalizedStrings from 'react-native-localization';

// CommonJS syntax
// let LocalizedStrings  = require ('react-native-localization');

let strings = new LocalizedStrings({
 en:{
   text:"Text",
   afterdinner:"After Dinner",
   beforebreakfast:"Before Breakfast",
   afterbreakfast:"After Breakfast",
   beforedinner : "Before Dinner",
   bedtime  :'Bed Time',
   afterlunch  :'After Lunch',
   beforelunch : 'Before Lunch',
   tillrequired  :'Till Required',
   tocontinue : 'To Continue',
   sos : 'SOS',
   frequency : 'Frequency',
   duration : 'Duration',
   symptoms  :'Symptoms',
   findings :'Findings',
   diagnosis :'Diagnosis',
   advisedinvestigation :'Advised Investigations',
   instructions  :'Instructions',
   followup :'Followup',
   
   pres : 'Prescription',
   notes : 'Notes',
   referto : 'Refer to',
   medicine : 'Medicines',
   timingandduration : 'Timing & Duration',
   note : 'Note',


 },
 be: {
  text:"পাঠ্য",
  afterdinner:"রাতের খাওয়ার পরে",
  beforebreakfast:"প্রাতরাশের আগে",
  afterbreakfast:"প্রাতরাশের পরে",
  beforedinner : "রাতে খাওয়ার আগে",
  bedtime  :'শোয়ার সময়',
  afterlunch  :'দুপুরের খাওয়ার পরে',
  beforelunch : 'দুপুরের খাওয়ার আগে',
  tillrequired  :'প্রয়োজন থাকা পর্যন্ত',
  tocontinue : 'চালু রাখতে হবে',
  sos : 'আপৎকালীন প্রয়োজনীয়তা',
  frequency : 'পৌনঃপুনিকতা',
  duration : 'মেয়াদ',
  symptoms  :'উপসর্গ', //d
  findings :'আবিষ্কার', //d
  diagnosis :'রোগ নির্ণয়',//
  advisedinvestigation :'সুপারিশকৃত অনুসন্ধান',// d
  instructions  :'নির্দেশিকা',//d
  followup :'অনুসরণ',//d
  
  pres : 'প্রেসক্রিপশন',
  notes : 'নোটস',
  referto : 'দেখুন',
  medicine : 'ওষুধ',
  timingandduration : 'খাওয়ার সময় এবং মেয়াদ',
  note : 'বিঃদ্রঃ',
 },
 gu: {
  text:"લખાણ",
  afterdinner:"રાત્રીભોજન પછી",
  beforebreakfast:"નાસ્તા પહેલા",
  afterbreakfast:"નાસ્તા પછી",
  beforedinner : "રાત્રીભોજન પહેલા",
  bedtime  :'ઉંઘનો સમય',
  afterlunch  :'બપોરના ભોજન પછી',
  beforelunch : 'પોરના ભોજન પહેલા',
  tillrequired  :'જરૂરી હોય ત્યાં સુધી',
  tocontinue : 'ચાલુ રાખવું',
  sos : 'એસઓએસ',
  frequency : 'આવર્તન',
  duration : 'સમયગાળો',
  symptoms  :'લક્ષણો',
  findings :'તારણો',
  diagnosis :'નિદાન',
  advisedinvestigation :'તપાસની સલાહ',
  instructions  :'સૂચના',
  followup :'ફોલો અપ',
  
  pres : 'પ્રિસ્ક્રીપ્શન',
  notes : 'નોંધ',
   referto : 'ને સંદર્ભ',
   medicine : 'દવાઓ',
   timingandduration : 'સમય અને સમયગાળો',
   note : 'નૉૅધ',
 },
 ma: {
  text:"मजकूर",
  afterdinner:"रात्रीच्या जेवणानंतर",
  beforebreakfast:"न्याहारीच्या आधी",
  afterbreakfast:"न्याहारीनंतर",
  beforedinner : "रात्रीच्या जेवणाच्या आधी",
  bedtime  :'झोपतांना',
  afterlunch  :'दुपारीच्या जेवणानंतर',
  beforelunch : 'दुपारीच्या जेवणाच्या आधी',
  tillrequired  :'आवश्यक होईपर्यंत',
  tocontinue : 'चालू ठेवा',
  sos : 'SOS',
  frequency : 'वारंवारता',
  duration : 'कालावधी',
  symptoms  :'लक्षणे',
  findings :'निष्कर्ष',
  diagnosis :'रोगनिदान',
  advisedinvestigation :'पडताळणीचा सल्ला',
  instructions  :'सूचना',
  followup :'पाठलाग',
   
  pres : 'प्रिस्क्रिप्शन',
  notes : 'टिप',
   referto : 'याचा संदर्भ घ्या',
   medicine : 'औषधे',
   timingandduration : 'वेळ व कालावधि',
   note : 'नोंद',
 },
 hi: {
  text:"मूलपाठ",
  afterdinner:"रात के खाने के बाद",
  beforebreakfast:"नाश्ते से पहले",
  afterbreakfast:"नाश्ते के बाद",
  beforedinner : "रात के खाने से पहले",
  bedtime  :'सोने का समय',
  afterlunch  :'दोपहर के भोजन के बाद',
  beforelunch : 'दोपहर के भोजन से पहले',
  tillrequired  :'जब तक आवश्यकता हो',
  tocontinue : 'जारी रखने के लिए',
  sos : 'एसओएस (आवश्यकतानुसार)',
  frequency : 'आवृत्ति',
  duration : 'अवधि',
  symptoms  :'लक्षण (निष्कर्ष)',
  findings :'जाँच - परिणाम',
  diagnosis :'निदान',
  advisedinvestigation :'सलाह अनुसार जाँच ',
  instructions  :'निर्देश',
  followup :'फॉलोअप (बार बार जाना)',
  
  pres : 'प्रिस्क्रिप्शन',
  notes : 'टिप्पणियाँ',
  referto : 'संदर्भ लें',
  medicine : 'दवाइयाँ',
  timingandduration : 'समय और अवधि',
  note : 'ध्यान दें',
 },
 ta: {
  text:"உரை",
  afterdinner:"இரவு உணவிற்குப்பின்",
  beforebreakfast:"காலை உணவிற்கு முன்",
  afterbreakfast:"காலை உணவிற்கு பின்",
  beforedinner : "இரவு உணவிற்கு முன்",
  bedtime  :'படுக்கும் நேரம்',
  afterlunch  :'மதிய உணவிற்கு பின்',
  beforelunch : 'மதிய உணவிற்கு முன்',
  tillrequired  :'தேவைப்படும் வரை',
  tocontinue : 'தொடரவும்',
  sos : 'SOS',
  frequency : 'தடவை',
  duration : 'தடவை',
  symptoms  :'அறிகுறிகள்',
  findings :'கண்டுபிடிப்புகள்',
  diagnosis :'நோய் கண்டறிதல்',
  advisedinvestigation :'அறிவுறுத்தப்பட்ட பரிசோதனை',
  instructions  :'வழிகாட்டு நெறிமுறைகள்',
  followup :'பின்பற்றுதல்',

   pres : 'மருந்துச்சீட்டு',
   notes : 'குறிப்புகள்',
   referto : 'குறிப்புகள்',
   medicine : 'மருந்துகள்',
   timingandduration : 'நேரம் & கால அளவு',
   note : 'குறிப்பு',
 },
 te: {
  text:"టెక్ట్స్",
  afterdinner:"డిన్నర్ తరువాత",
  beforebreakfast:"బ్రేక్ ఫాస్ట్ కి ముందు",
  afterbreakfast:"బ్రేక్ ఫాస్ట్ కి తరువాత",
  beforedinner : "డిన్నర్ కి ముందు",
  bedtime  :'నిద్రించే సమయం',
  afterlunch  :'లంచ్ తరువాత',
  beforelunch : 'లంచ్ కి ముందు',
  tillrequired  :'కావల్సినంత వరకు',
  tocontinue : 'కొనసాగించడానికి',
  sos : 'ఎస్ఓఎస్',
  frequency : 'తరచుదనం',
  duration : 'వ్యవధి',
  symptoms  :'లక్షణాలు',
  findings :'తెలుసుకున్నవి',
  diagnosis :'వ్యాధి నిర్థారణ',
  advisedinvestigation :'సలహా ఇవ్వబడిన పరీక్ష',
  instructions  :'ఆదేశాలు',
  followup :'ఫాలో అప్',

   pres : 'ప్రిస్క్రిప్షన్',
   notes : 'నోట్స్',
   referto : 'కి సూచించండి',
   medicine : 'మందులు',
   timingandduration : 'సమయం & వ్యవధి',
   note : 'గమనిక',
 }
})
export default {
    language: strings,
};


